### ISSUE TITLE
Theme didn't work?

### ISSUE THREAD

**Issue by balwaniPrem** [cognitom/ModernAqua-Theme-for-SugarCRM#12]
Was able to install the theme by re-zipping only the needed files, and no issues reported in installation but looks like new theme didn't take effect? 

Am i missing something? Newbie at SugarCRM. I set the theme as default under theme settings. 

SugarCRM CE - 6.5.16

**Comment by balwaniPrem** [comment]
Quick update, i tried different permissions in cache folder (777, & 775) but it still doesn't seem to be working.

**Comment by ernierasta** [comment]
I am not working with sugar any more, seek sugarcrm forums for help.
Have nice day anyway ;-)
