### ISSUE TITLE
Support for v6

### ISSUE THREAD

**Issue by Auronmatrix** [cognitom/ModernAqua-Theme-for-SugarCRM#5]

**Comment by Auronmatrix** [comment]
Sorry, I hit enter before I could type the description >.<

**Comment by ernierasta** [comment]
Ok, so I am waiting for problem description.

**Comment by Auronmatrix** [comment]
> .< it is in the other ticket, did not realize it created 2. Delete this one?

**Comment by ernierasta** [comment]
yeah ;-)
