### ISSUE TITLE
Unified search will revert to previous page automatically after displaying results 

### ISSUE THREAD

**Issue by dauclair** [cognitom/ModernAqua-Theme-for-SugarCRM#7]
Description: This is an issue that has already been fixed in Classic theme, but still exists in ModernAqua. When performing a search using the "unified searchbox" on the bottom left of the screen, after the results page loads you get automatically reverted back to the previous page you were viewing. 

Solution: The action='index.php' is missing from the form tag in /themes/ModernAqua/tpls/_headerSearch.tpl. Add the form action and it should behave properly. Please see the following pull request diff for code example: https://github.com/sugarcrm/sugarcrm_dev/pull/61/files

**Comment by ernierasta** [comment]
Thanx man for great info, i will look at it!

Greeting 

Leszek

**Comment by ernierasta** [comment]
Fixed, thank you very much!

**Comment by dauclair** [comment]
Dear Valued Rio Client,

I will be out of the office working on-location in San Diego Tuesday, March 20, 2012 and returning on Wednesday, March 21, 2012. I will have limited access to my email and cell phone during this time, so I will not be able to respond as quickly as I would like.

If you need immediate assistance, please contact me on my cell phone or call our main office number at: (858) 523-8746. Thank you for your patience and understanding, as you are very important to me. I hope you have a wonderful day!

Daryl Auclair
Web Developer / SEO Guru
Rio Online Development, Inc.

Phone: 858.523.8746
Email: daryl@riodevelopment.com

Visit us online at www.riodevelopment.com
