### ISSUE TITLE
Issue with v.6.4.3

### ISSUE THREAD

**Issue by FlexibleTax** [cognitom/ModernAqua-Theme-for-SugarCRM#9]
Hi,

It's almost working perfectly. Only, with the tabs on the left side, some tabs like Contact, Leads... I only see: 
Error:
{"content":"

On a new window.

Can you please have a look?
My version is 6.4.3 and I use all the files from this site (for the theme)

Thank you!

**Comment by FlexibleTax** [comment]
I just figure out. Make a repair in the admin menu fix it. Thank you anyway :) and keep doing your great job!!!

**Comment by sushimatt** [comment]
I am running Version 6.3.0 (Build 7004) and still have the same problem for the first 4 tabs. otherwise works beautiful, but I have the {"content":" display in a box for the main tabs... a rebuild does not seem to solve it.
